name: Heloo world workflow

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

 workflow_dispatch:
   

jobs:
 Hello_world:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: run a one-line script
      run: ls -a