name: Hello ya World

on:
 push:
   branches: [ "main" ]
 pull_request: 
   branches: [ "main" ]
 workflow_dispatch:
   
jobs:
 ubuntu:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, World from ubuntu!

 Mac:
   runs-on: macos-10.15
   steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, World from mac!
 Windows:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, World from Windows!