---
name: testing env
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch: null

jobs:
  Build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello world ubuntu

   Build_MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello world MacOs